@host= http://localhost:8787
# @host= https://aircnc.deno.dev
@token= {{$dotenv JWT_TOKEN}}

POST {{host}}/api/v1/emails?action=bookingConfirmation
Content-Type: application/json
Authorization:Bearer {{token}}

{
    "email":"jitunayak715@gmail.com",
    "name":"Jitu Nayak",
    "bookingId":"89923",    
    "checkInDate":"22/05/2024",
	"checkOutDate":"24/05/2024"
}