@host= http://localhost:8787
# @host= https://aircnc.deno.dev
@userId=fada82b0-3101-42d3-9b7b-0b7b386a4c78
@token= {{$dotenv JWT_TOKEN}}


### Get all rooms
GET {{host}}/api/v1/rooms
Authorization: Bearer {{token}}