@host= http://localhost:8787
@userId=fada82b0-3101-42d3-9b7b-0b7b386a4c78

### get all wishlists
GET {{host}}/api/v1/wishlists


### 
# @name createWishlist
POST {{host}}/api/v1/wishlists
Content-Type: application/json

{
    "userId": "{{userId}}",
    "roomId": "14"
}

### Get wishlists for a user
GET {{host}}/api/v1/wishlists/{{createWishlist.response.body.id}}
